<?xml version="1.0" encoding="UTF-8"?>
<project name="ShoppingBasketGUI" default="run">
    <property name="src" location="src"/>
    <property name="build" location="build"/>
    <property name="classes" location="${build}/classes"/>
    <property name="jar" location="${build}/ShoppingBasketGUI.jar"/>

    <target name="clean">
        <delete dir="${build}"/>
    </target>

    <target name="compile" depends="clean">
        <mkdir dir="${classes}"/>
        <javac srcdir="${src}" destdir="${classes}"/>
    </target>

    <target name="jar" depends="compile">
        <jar destfile="${jar}" basedir="${classes}">
            <manifest>
                <attribute name="Main-Class" value="ShoppingBasketGUI"/>
            </manifest>
        </jar>
    </target>

    <target name="run" depends="jar">
        <java jar="${jar}" fork="true"/>
    </target>
</project>
